swagger: "2.0"
info:
  title: demo
  description: demo
  version: 1.0.0
paths:
  /method:
    post:
      security: []
      operationId: demo.method
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        schema:
          type: object
          properties:
            param1:
              type: string
      responses:
        200:
          description: Payment details
          schema:
            type: object
            properties:
              time:
                type: string
securityDefinitions:
  basicAuth:
    type: basic
